KS-3-2 Name, Lastname
RaveBear/KotlinSprint pull request #12
Opened 2023-09-24 08:49 UTC by RaveBear

2023-09-24 16:07 UTC, ievetrov requested changes

2023-09-24 16:07 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    println("ФИО: " + lastname + " " + name + " " + surname + ", " + "Возраст: " + age + " года")
корректно! однако предлагаю использовать непосредственно фичи Котлин. а именно не конкатенацию, а интерполяцию

2023-09-25 19:33 UTC, RaveBear commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    println("ФИО: " + lastname + " " + name + " " + surname + ", " + "Возраст: " + age + " года")
Сделано!

2023-09-26 10:31 UTC, ievetrov approved these changes
ок!

2023-09-26 17:53 UTC, merged