KS-3-3 Multiplication table
RaveBear/KotlinSprint pull request #13
Opened 2023-09-24 10:23 UTC by RaveBear

2023-09-24 16:13 UTC, ievetrov requested changes

2023-09-24 16:13 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_3.kt
> +        4 * 1 = ${4 * 1}
отлично, но мы же создали number. давай использовать эту переменную, чтобы программа стала универсальной

2023-09-25 19:37 UTC, RaveBear commented on src/main/kotlin/lesson_3/lesson_3_task_3.kt
> +        4 * 1 = ${4 * 1}
Сделано!

2023-09-26 10:31 UTC, ievetrov approved these changes

2023-09-26 17:54 UTC, merged