KS-3-4 Chess
RaveBear/KotlinSprint pull request #14
Opened 2023-09-24 10:42 UTC by RaveBear

2023-09-26 10:48 UTC, ievetrov requested changes

2023-09-26 10:48 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
> +    println("Ход номер $moveNumber: $moveFrom-$moveIn")
Обращаю внимание на пример строки для отправки на сервер [откуда-куда;номер хода]
В условии не случайно уточнен выводимый формат. Если формат готовой строки будет отличаться, то сервер не сможет ее распарсить и программа может упасть/не работать итд.
Предлагаю привести формат в соответствие с форматов в ТЗ)

2023-09-26 18:07 UTC, RaveBear commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
> +    println("Ход номер $moveNumber: $moveFrom-$moveIn")
Исправил!

2023-09-27 09:34 UTC, ievetrov approved these changes
ок!

2023-09-27 20:09 UTC, merged