KS-4-2 Cargo weight and volume
RaveBear/KotlinSprint pull request #17
Opened 2023-09-26 19:11 UTC by RaveBear

2023-09-27 07:38 UTC, ievetrov requested changes

2023-09-27 07:38 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +//val WEIGHT_AVERAGE_CARGO = 35..100
ненужные комменты лучше удалять

2023-09-27 07:38 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +            "${(weightCargo2 >= MIN_WEIGHT_AVERAGE_CARGO) && (weightCargo2 < MAX_WEIGHT_AVERAGE_CARGO)
здесь также должно быть `weightCargo2 <= MAX_WEIGHT_AVERAGE_CARGO`

2023-09-27 20:44 UTC, RaveBear commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +            "${(weightCargo2 >= MIN_WEIGHT_AVERAGE_CARGO) && (weightCargo2 < MAX_WEIGHT_AVERAGE_CARGO)
Почему ? Ведь в задании сказано "Напиши программу, которая проверяет, соответствует ли груз категории "Average". Эта категория имеет следующие параметры: вес от 35 кг до 100 кг (включительно), **и объем меньше 100 литров.**"
Объем меньше 100 л )) или я не так понял ? 
Исправил в соответствии с твоим комментарием

2023-09-28 02:59 UTC, ievetrov requested changes

2023-09-28 02:59 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +            "${(weightCargo2 >= MIN_WEIGHT_AVERAGE_CARGO) && (weightCargo2 < MAX_WEIGHT_AVERAGE_CARGO)
объем то правильно был сделан)) `volumeCargo2 < VOLUME_AVERAGE_CARGO`, как и в верхнем сравнении

я писал про вот эту часть `weightCargo2 < MAX_WEIGHT_AVERAGE_CARGO`, там должно быть меньше или равно) потому что сейчас у тебя максимальный вес не включительно сделан

2023-09-28 16:22 UTC, RaveBear commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +            "${(weightCargo2 >= MIN_WEIGHT_AVERAGE_CARGO) && (weightCargo2 < MAX_WEIGHT_AVERAGE_CARGO)
Исправил ) Не внимательно посмотрел

2023-09-29 06:46 UTC, ievetrov approved these changes

2023-09-30 16:00 UTC, merged