KS-4-5 Ship at sea
RaveBear/KotlinSprint pull request #20
Opened 2023-10-01 14:35 UTC by RaveBear

2023-10-02 07:45 UTC, ievetrov requested changes

2023-10-02 07:45 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    println("Повреждения отсутствуют?: ")
такой вопрос сбивает с толку, если пользователь введет `true`, то повреждения будут присутствовать

2023-10-02 07:45 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +val ALT_CREW_SIZE = 70
эти переменные дублируют константы сверху, давай их удалим

2023-10-02 07:45 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    if ((damage == HAS_NO_DAMAGE) && (crewSize in MIN_CREW_SIZE..MAX_CREW_SIZE || crewSize >= ALT_CREW_SIZE)
может разбить эти 2 условия на 2 `if`? сейчас это очень сложно читать)

2023-10-02 18:26 UTC, RaveBear commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    println("Повреждения отсутствуют?: ")
Исправил на IS_ANY_DAMAGE

2023-10-04 20:06 UTC, RaveBear commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +val ALT_CREW_SIZE = 70
Удалил

2023-10-04 20:10 UTC, RaveBear commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    if ((damage == HAS_NO_DAMAGE) && (crewSize in MIN_CREW_SIZE..MAX_CREW_SIZE || crewSize >= ALT_CREW_SIZE)
Вроде поправил. Но все равно не правильно работает ((
Если в первом if все условия true, а в else if условия не true, то все равно показывает, что Плавание разрешено и наоборот. Я понимаю почему так происходит. Но нам же нужно, чтоб все 4 условия были true для того, чтоб плавание было разрешено. А сейчас получается, что плавание разрешено, когда соблюдены только два условия в первом блоке if или во втором else if.
Я чет подзавис тут, помоги пожалуйста

2023-10-05 06:28 UTC, ievetrov approved these changes

2023-10-05 18:11 UTC, merged