KS-5-1 User authorization
RaveBear/KotlinSprint pull request #21
Opened 2023-10-01 17:44 UTC by RaveBear

2023-10-02 09:05 UTC, ievetrov requested changes

2023-10-02 09:05 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +const val RIGHT_ANSWER = 7
Нам необходимо думать об обслуживании и расширяемости кода. Сумма должна считаться автоматически из объявленных заранее переменных.

2023-10-03 20:19 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +const val RIGHT_ANSWER = 7
Исправил

2023-10-04 06:38 UTC, ievetrov requested changes

2023-10-04 06:38 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val rightAnswer = 2 + 5
Значение в этом коде является [магическим числом](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2023-10-04 06:38 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    println("Подтвердите, что Вы не робот. Решите задачу: 2 + 5 =")
также код повторяется. не соблюдается принцип [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself)

нам следует думать о поддерживаемости и расширяемости кода. если мы заходим изменить числа в примере, то это придется сразу в 4 местах менять) а программа обычно еще больше строк кода содержит

2023-10-04 20:24 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val rightAnswer = 2 + 5
Исправил

2023-10-04 20:27 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    println("Подтвердите, что Вы не робот. Решите задачу: 2 + 5 =")
Исправил

2023-10-05 11:50 UTC, ievetrov approved these changes
окей!

2023-10-05 18:12 UTC, merged