KS-5-3 Lottery
RaveBear/KotlinSprint pull request #23
Opened 2023-10-01 19:54 UTC by RaveBear

2023-10-02 09:24 UTC, ievetrov requested changes

2023-10-02 09:24 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if (userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber == SECOND_WIN_NUMBER) {
тут не учтено, что числа могут быть введены в обратном порядке и оба верные)

2023-10-02 09:24 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if ((userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) ||
сейчас у тебя каждый if живет по отдельности и каждая ветка будет проверяться.
нужно сделать его общей сущностью, поэтому тут лучше использовать else if. тогда условие выше точно будет отсекаться и в этом условии будет достаточно только проверить все возможные совпадения через ИЛИ

(не используя исключение отрицания)

2023-10-02 09:24 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if (userFirstNumber != FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) {
и завершающая ветка тоже должна быть частью общего if. а именно else {} - будет выполняться, если все остальные варианты не сработали

2023-10-03 20:46 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if (userFirstNumber != FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) {
Исправил

2023-10-03 20:46 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if ((userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) ||
Исправил

2023-10-04 06:41 UTC, ievetrov requested changes

2023-10-04 06:41 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    if (userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber == SECOND_WIN_NUMBER) {
не исправлено. надо добавить еще проверку ввода, если в первое число было введено правильное число из второй константы

2023-10-04 06:41 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else if ((userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) ||
проверка на НЕ равенство тут лишняя. достаточно сделать на проверку любого числа, перечисляя варианты через ИЛИ

2023-10-04 06:41 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else {userFirstNumber != FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER
а что делает эта строка?
`else {userFirstNumber != FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER}`

2023-10-04 20:47 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else if ((userFirstNumber == FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER) ||
Исправил

2023-10-04 20:48 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_3.kt
> +    } else {userFirstNumber != FIRST_WIN_NUMBER && userSecondNumber != SECOND_WIN_NUMBER
Затупил! Она вообще не нужна! :)

2023-10-05 11:51 UTC, ievetrov approved these changes
отлично!

2023-10-05 18:13 UTC, merged