KS-5-4 Heart of Gold
RaveBear/KotlinSprint pull request #24
Opened 2023-10-05 19:22 UTC by RaveBear

2023-10-06 09:28 UTC, ievetrov requested changes

2023-10-06 09:28 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_4.kt
> +        "\nПользователь \"Zaphod\", вам разрешено входить на борт корабля \"Heart of Gold\"")
название пользователя лучше использовать из переменной, чтобы программа была гибче и обрабатывала разных входящих пользователей

2023-10-06 18:20 UTC, RaveBear commented on src/main/kotlin/lesson_5/lesson_5_task_4.kt
> +        "\nПользователь \"Zaphod\", вам разрешено входить на борт корабля \"Heart of Gold\"")
Понял, вспомнил, исправил ))

2023-10-07 17:43 UTC, ievetrov approved these changes

2023-10-07 18:01 UTC, merged