KS-6-2 Simple timer
RaveBear/KotlinSprint pull request #27
Opened 2023-10-10 14:38 UTC by RaveBear

2023-10-11 16:04 UTC, ievetrov requested changes

2023-10-11 16:04 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    while (userSeconds > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2023-10-13 13:46 UTC, ievetrov requested changes

2023-10-13 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
>          println("Прошло ${userSeconds--} секунд")
отсутствует форматирование (отступы)

2023-10-13 13:46 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
>          Thread.sleep(1000)
программа остановится на 1 секунду. а нужно на переданное количество секунд пользователем

2023-10-15 09:25 UTC, ievetrov requested changes

2023-10-15 09:25 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    println("Прошло ${userSeconds--} секунд")
а зачем декремент? который отнимет единицу после вывода строки, но больше нигде не заиспользуется

2023-10-15 10:56 UTC, RaveBear commented on src/main/kotlin/lesson_6/lesson_6_task_2.kt
> +    println("Прошло ${userSeconds--} секунд")
Да, не нужен, это уже я поторопился закончить ))

2023-10-16 08:15 UTC, ievetrov approved these changes

2023-10-17 19:17 UTC, merged