KS-7-3 Even numbers
RaveBear/KotlinSprint pull request #33
Opened 2023-10-19 19:41 UTC by RaveBear

2023-10-20 15:44 UTC, ievetrov requested changes

2023-10-20 15:44 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +    val range1 = 0..userNumber
Предлагаю избавиться от переменной и сразу использовать прогрессию в цикле. Это не должно сильно испортить читаемость.

2023-10-20 15:44 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +    val range1 = 0..userNumber
почему название c индексом 1?

2023-10-20 15:44 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +        if (x % 2 == 0)
Можно сделать еще проще. попробуй применить шаг диапазона

2023-10-22 10:31 UTC, RaveBear commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +    val range1 = 0..userNumber
> почему название c индексом 1?

Затупил ))

2023-10-22 10:31 UTC, RaveBear commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +    val range1 = 0..userNumber
Исправил

2023-10-22 10:40 UTC, RaveBear commented on src/main/kotlin/lesson_7/lesson_7_task_3.kt
> +        if (x % 2 == 0)
Испарвил

2023-10-23 12:09 UTC, ievetrov approved these changes

2023-10-24 18:54 UTC, merged