KS-1-4 Variable type
RaveBear/KotlinSprint pull request #4
Opened 2023-09-08 10:19 UTC by RaveBear

2023-09-08 18:59 UTC, ievetrov requested changes

2023-09-08 18:59 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_4.kt
> +    val partOfYear: Float = 2.0547945205479453E-4f
а ты пробовал распечатать это значение?)
оно округлится и будет отличаться от исходного

2023-09-09 05:23 UTC, RaveBear commented on src/main/kotlin/lesson_1/lesson_1_task_4.kt
> +    val partOfYear: Float = 2.0547945205479453E-4f
Исправил))

2023-09-10 05:18 UTC, ievetrov approved these changes

2023-09-12 13:14 UTC, merged