KS-1-5 Second to hh.mm.ss
RaveBear/KotlinSprint pull request #5
Opened 2023-09-09 13:06 UTC by RaveBear

2023-09-10 19:35 UTC, ievetrov requested changes

2023-09-10 19:35 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$hour:$minutes:$seconds") /* не знаю как сделать так,
попробуй использовать для этого `String.format`)

2023-09-12 19:46 UTC, ievetrov requested changes

2023-09-12 19:46 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$minutes:$s")
минуты по прежнему не отформатированы)

2023-09-12 19:46 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$minutes:$s")
и предлагаю как-то единообразно назвать переменные, а то минуты выбиваются из общей картины и влияет на читаемость кода

2023-09-12 19:46 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$minutes:$s")
если будет 1 минута, то ноль не подставится

2023-09-13 07:23 UTC, RaveBear commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$minutes:$s")
Исправил

2023-09-13 07:23 UTC, RaveBear commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$minutes:$s")
Исправил

2023-09-14 05:20 UTC, ievetrov approved these changes

2023-09-14 05:20 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("$h:$m:$s")
все правильно) только на будущее тут можно было сократить код до такого варианта:
`println(String.format("%02d:%02d:%02d", hour, minutes, seconds))`

2023-09-19 19:06 UTC, merged