KS-2-1 Grade point average (GPA)
RaveBear/KotlinSprint pull request #6
Opened 2023-09-09 13:47 UTC by RaveBear

2023-09-12 07:04 UTC, ievetrov requested changes

2023-09-12 07:04 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_1.kt
> +    val GPA = (grades1+grades2+grades3+grades4) * 4 / 16
решение верное, однако есть что надо доработать. 
- все арифметические знаки обосабливаются пробелами
- название переменной в текущей реализации больше похоже на константу. для обычных переменных всегда используется camelCase
- недопонял зачем умножать на 4, а затем делить на 16) вроде бы можно сразу поделить на 4

2023-09-13 07:29 UTC, RaveBear commented on src/main/kotlin/lesson_2/lesson_2_task_1.kt
> +    val GPA = (grades1+grades2+grades3+grades4) * 4 / 16
1. Исправил
2. Исправил
3. Исправил. Изначально подумал, что каждый ученик получил по 4 оценки, итого получилось 16 оценок. Поэтому сначала сложил оценки одного ученика и умножил на 4 учеников, а дальше разделил на количество оценок (16).

2023-09-13 18:55 UTC, ievetrov approved these changes
ок!

2023-09-19 19:10 UTC, merged