KS-2-3 Train schedule
RaveBear/KotlinSprint pull request #8
Opened 2023-09-19 21:24 UTC by RaveBear

2023-09-20 10:28 UTC, ievetrov requested changes

2023-09-20 10:28 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    val hourOfdeparture = 9
каждое новое слово начинается с заглавной буквы
hourOfDeparture

2023-09-20 10:28 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println(String.format("Время прибытия: %d:%d", arrivalTimeHours, arrivalTimeMinutes))
чтобы даже однозначное значение выводилось с нулем, при форматировании следует использовать такой шаблон %02d

2023-09-20 20:11 UTC, RaveBear commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    val hourOfdeparture = 9
Исправил

2023-09-20 20:11 UTC, RaveBear commented on src/main/kotlin/lesson_2/lesson_2_task_3.kt
> +    println(String.format("Время прибытия: %d:%d", arrivalTimeHours, arrivalTimeMinutes))
Исправил

2023-09-21 09:27 UTC, ievetrov approved these changes
отлично. а эти шаблоны называются спецификаторы форматирование. подробнее тут https://hr-vector.com/java/formatirovanie-chisel-strok

2023-09-23 07:55 UTC, merged